export { validate as emailValidation } from './email'
export { validate as passwordValidation } from './password'
export { validate as loginValidation } from './login'
export { validate as nameValidation } from './name'
export { validate as phoneValidation } from './phone'
